import type { Notification, PortfolioProject, Profile, Project, Proposal, Review, Service } from "@/types/domain";

export const services: Service[] = [
  { id: "svc-1", category: "Design", name: "Full Home Interior Design", slug: "full-home-interior-design", roleScope: ["designer"], description: "Concept, space planning, materials, and execution-ready drawings." },
  { id: "svc-2", category: "Design", name: "Modular Kitchen Design", slug: "modular-kitchen-design", roleScope: ["designer"], description: "Kitchen layouts, storage planning, finishes, and vendor-ready details." },
  { id: "svc-3", category: "Ceiling", name: "False Ceiling", slug: "false-ceiling", roleScope: ["contractor"], description: "Gypsum, POP, lighting coves, rafters, and ceiling execution." },
  { id: "svc-4", category: "Wall", name: "Wall Paneling", slug: "wall-paneling", roleScope: ["designer", "contractor"], description: "Feature walls, fluted panels, veneer, paint, texture, and cladding." },
  { id: "svc-5", category: "Flooring", name: "Flooring Installation", slug: "flooring-installation", roleScope: ["contractor"], description: "Tile, wooden, vinyl, stone, and floor preparation work." },
  { id: "svc-6", category: "Execution", name: "End-to-End Execution", slug: "end-to-end-execution", roleScope: ["contractor"], description: "Site coordination, procurement, labour, and handover support." },
  { id: "svc-7", category: "Design", name: "Bedroom Makeover", slug: "bedroom-makeover", roleScope: ["designer", "contractor"], description: "Wardrobes, walls, lighting, furnishing, and small-room transformation." },
  { id: "svc-8", category: "Execution", name: "Carpentry & Wardrobes", slug: "carpentry-wardrobes", roleScope: ["contractor"], description: "Custom wardrobes, storage, TV units, partitions, and finish carpentry." },
];

export const profiles: Profile[] = [
  {
    id: "cust-1",
    fullName: "Aarav Sharma",
    email: "customer@sajivo.com",
    primaryRole: "customer",
    roles: ["customer"],
    city: "Bengaluru",
    state: "Karnataka",
    bio: "Renovating a compact apartment with clear budgets and staged execution.",
  },
  {
    id: "des-1",
    fullName: "Meera Iyer",
    email: "designer@sajivo.com",
    primaryRole: "designer",
    roles: ["designer"],
    city: "Bengaluru",
    state: "Karnataka",
    businessName: "Studio Meera",
    bio: "Warm modern interiors, modular planning, and compact luxury homes.",
    yearsExperience: 8,
    serviceAreas: ["Indiranagar", "Whitefield", "HSR Layout"],
    services: ["Full Home Interior Design", "Modular Kitchen Design", "Bedroom Makeover"],
    startingPrice: 75000,
    availabilityStatus: "Taking projects from next month",
    verificationStatus: "verified",
    ratingAvg: 4.8,
    reviewsCount: 42,
  },
  {
    id: "con-1",
    fullName: "Kabir Khan",
    email: "contractor@sajivo.com",
    primaryRole: "contractor",
    roles: ["contractor"],
    city: "Bengaluru",
    state: "Karnataka",
    businessName: "Khan BuildWorks",
    bio: "Execution team for ceilings, panels, carpentry, flooring, and final handover.",
    yearsExperience: 11,
    serviceAreas: ["Bengaluru", "Mysuru"],
    services: ["False Ceiling", "Wall Paneling", "Flooring Installation", "End-to-End Execution"],
    specializations: ["False ceiling", "Carpentry", "Site execution"],
    projectSizeRange: "Rs 2L - Rs 50L",
    availabilityStatus: "2 slots available",
    verificationStatus: "verified",
    ratingAvg: 4.7,
    reviewsCount: 64,
  },
  {
    id: "ven-1",
    fullName: "Riya Materials",
    email: "vendor@sajivo.com",
    primaryRole: "vendor",
    roles: ["vendor"],
    accountType: "business",
    businessAccountType: "vendor",
    businessRole: "retailer",
    city: "Bengaluru",
    state: "Karnataka",
    businessName: "Riya Materials",
    bio: "Verified retailer for interior finishes, hardware, flooring, and lighting.",
    verificationStatus: "verified",
  },
];

export const projects: Project[] = [
  {
    id: "proj-1",
    customerId: "cust-1",
    title: "2BHK living room and kitchen refresh",
    description: "Need a practical, warm, low-maintenance design with modular kitchen changes, TV wall, lighting, and storage.",
    status: "receiving_proposals",
    scopeType: "multi_room",
    scopeLabel: "Living Room, Kitchen",
    services: ["Modular Kitchen Design", "Wall Paneling", "False Ceiling"],
    city: "Bengaluru",
    state: "Karnataka",
    locality: "Indiranagar",
    budgetRange: "Rs 5,00,000 - Rs 10,00,000",
    expectedTimeline: "8-10 weeks",
    filesCount: 4,
    proposalsCount: 3,
    createdAt: new Date(Date.now() - 4 * 86_400_000).toISOString(),
    publishedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
  },
  {
    id: "proj-2",
    customerId: "cust-1",
    title: "Bedroom wardrobe and study corner",
    description: "A single-room upgrade with wardrobe redesign, compact work desk, and acoustic wall paneling.",
    status: "draft",
    scopeType: "single_room",
    scopeLabel: "Bedroom",
    services: ["Bedroom Makeover", "Carpentry & Wardrobes"],
    city: "Bengaluru",
    state: "Karnataka",
    locality: "HSR Layout",
    budgetRange: "Rs 1,00,000 - Rs 3,00,000",
    expectedTimeline: "4 weeks",
    filesCount: 1,
    proposalsCount: 0,
    createdAt: new Date(Date.now() - 1 * 86_400_000).toISOString(),
  },
  {
    id: "proj-3",
    customerId: "cust-1",
    title: "Complete villa interiors",
    description: "End-to-end interiors for a villa with design, ceiling, lighting, stone, wardrobes, and site coordination.",
    status: "in_progress",
    scopeType: "complete_property",
    scopeLabel: "Villa",
    services: ["Full Home Interior Design", "End-to-End Execution"],
    city: "Bengaluru",
    state: "Karnataka",
    locality: "Whitefield",
    budgetRange: "Above Rs 10,00,000",
    expectedTimeline: "20 weeks",
    filesCount: 12,
    proposalsCount: 8,
    selectedProfessionalId: "des-1",
    createdAt: new Date(Date.now() - 40 * 86_400_000).toISOString(),
    publishedAt: new Date(Date.now() - 38 * 86_400_000).toISOString(),
  },
];

export const proposals: Proposal[] = [
  {
    id: "prop-1",
    projectId: "proj-1",
    customerId: "cust-1",
    professionalId: "des-1",
    professionalRole: "designer",
    professionalName: "Studio Meera",
    status: "shortlisted",
    proposedAmount: 850000,
    estimatedTimeline: "9 weeks",
    message: "We can retain the existing shell, redraw the kitchen storage, and create a clean warm-modern living zone.",
    deliverables: ["Concept design", "Material palette", "Execution drawings", "Vendor coordination"],
    createdAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
  },
  {
    id: "prop-2",
    projectId: "proj-1",
    customerId: "cust-1",
    professionalId: "con-1",
    professionalRole: "contractor",
    professionalName: "Khan BuildWorks",
    status: "submitted",
    proposedAmountMin: 620000,
    proposedAmountMax: 780000,
    estimatedTimeline: "7 weeks",
    message: "Our execution team can handle ceiling, paneling, flooring preparation, and kitchen installation coordination.",
    deliverables: ["Site measurement", "Execution schedule", "Procurement list", "Weekly updates"],
    createdAt: new Date(Date.now() - 1 * 86_400_000).toISOString(),
  },
];

export const notifications: Notification[] = [
  { id: "notif-1", userId: "cust-1", projectId: "proj-1", kind: "proposal_received", message: "Studio Meera submitted a proposal for your living room and kitchen refresh.", readAt: null, createdAt: new Date(Date.now() - 2 * 3_600_000).toISOString() },
  { id: "notif-2", userId: "des-1", projectId: "proj-3", kind: "workspace_message", message: "Aarav sent a workspace message on Complete villa interiors.", readAt: null, createdAt: new Date(Date.now() - 5 * 3_600_000).toISOString() },
];

export const portfolioProjects: PortfolioProject[] = [
  { id: "port-1", professionalId: "des-1", title: "Warm Minimal Apartment", category: "Full Home", description: "Compact 2BHK transformed with muted tones, storage walls, and warm lighting.", location: "Indiranagar", completionYear: 2025, servicesProvided: ["Full Home Interior Design", "Modular Kitchen Design"], isFeatured: true },
  { id: "port-2", professionalId: "con-1", title: "Commercial Ceiling Rollout", category: "Execution", description: "Fast-track ceiling and wall paneling for a 4,000 sq ft office.", location: "Whitefield", completionYear: 2026, servicesProvided: ["False Ceiling", "Wall Paneling"], isFeatured: true },
];

export const reviews: Review[] = [
  { id: "rev-1", projectId: "proj-3", customerId: "cust-1", professionalId: "des-1", rating: 5, reviewText: "Clear process, polished drawings, and very controlled material selection.", createdAt: new Date(Date.now() - 12 * 86_400_000).toISOString() },
  { id: "rev-2", projectId: "proj-3", customerId: "cust-1", professionalId: "con-1", rating: 5, reviewText: "Strong site discipline and transparent execution updates.", createdAt: new Date(Date.now() - 18 * 86_400_000).toISOString() },
];
