import { ArrowRight, FileText, ReceiptText, ShieldCheck } from "lucide-react";
import { DashboardHeader } from "@/components/sajivo/DashboardBlocks";
import { createClient } from "@/lib/supabase/server";

export default async function FinancePage() {
  const supabase = await createClient();
  const { data: auth } = supabase ? await supabase.auth.getUser() : { data: { user: null } };
  const { data: docs } = supabase && auth.user ? await supabase.from("financial_documents").select("public_id, document_type, document_number, total_amount, amount_paid, status, created_at").eq("account_id", auth.user.id).order("created_at", { ascending: false }) : { data: null };
  return <><DashboardHeader eyebrow="Project finance" title="Documents & payments" text="Invoices remain separate from payments, and receipts appear only after authoritative confirmation." /><section className="rounded-lg border border-[var(--rv-border)] bg-[var(--rv-surface)]"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--rv-border)] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-[var(--rv-terracotta-soft)] text-[var(--rv-terracotta)]"><FileText size={18} /></span><div><h2 className="font-bold">Financial document center</h2><p className="text-xs text-[var(--rv-ink-2)]">Invoices, quotations, receipts, and payment references</p></div></div><span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><ShieldCheck size={14} />Ledger verified</span></header><div className="divide-y divide-[var(--rv-border)]">{docs?.length ? docs.map((doc) => <div key={doc.public_id} className="flex flex-wrap items-center gap-4 p-5"><span className="grid h-9 w-9 place-items-center rounded-md bg-[var(--rv-surface-muted)]"><ReceiptText size={16} /></span><div className="min-w-0 flex-1"><p className="font-semibold">{doc.document_number}</p><p className="mt-1 text-xs capitalize text-[var(--rv-ink-2)]">{doc.document_type.replaceAll("_", " ")} · {doc.status}</p></div><p className="font-bold">₹{Number(doc.total_amount).toLocaleString("en-IN")}</p><ArrowRight size={16} className="text-[var(--rv-ink-2)]" /></div>) : <div className="p-10 text-center"><ReceiptText className="mx-auto text-[var(--rv-ink-2)]" size={28} /><h3 className="mt-3 font-bold">No financial documents yet</h3><p className="mt-1 text-sm text-[var(--rv-ink-2)]">Issued invoices and confirmed payment receipts will appear here.</p></div>}</div></section></>;
}
