import Link from "next/link";
import { ArrowRight, CheckCircle2, FileText, Search, SlidersHorizontal } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";

const journeys: Record<string, { title: string; intro: string; sections: Array<[string, string[]]>; cta: string }> = {
  "full-home-interior-design": { title: "Full Home Interior Design", intro: "Design your entire home with the right professionals, materials, and execution plan.", sections: [["Spaces", ["Living room", "Bedrooms", "Kitchen", "Bathrooms", "Dining", "Storage", "Lighting", "Flooring"]], ["Design styles", ["Modern", "Contemporary", "Minimal", "Luxury", "Traditional", "Scandinavian", "Industrial"]], ["Project brief", ["Room-by-room scope", "Material preferences", "Budget and timeline", "Professional matching"]]], cta: "Start My Home Project" },
  "modular-kitchen": { title: "Modular Kitchen", intro: "Configure a kitchen brief that professionals and suppliers can quote clearly.", sections: [["Layouts", ["L-shaped", "U-shaped", "Parallel", "Straight", "Island"]], ["Materials", ["Plywood", "MDF / HDF", "Laminates", "Acrylic", "Veneer", "Glass"]], ["Hardware and tops", ["Hinges", "Channels", "Baskets", "Lift-up systems", "Granite", "Quartz", "Marble"]]], cta: "Configure My Kitchen" },
  "false-ceiling": { title: "False Ceiling", intro: "Plan ceiling types, lighting, dimensions, and performance before you invite proposals.", sections: [["Ceiling types", ["Gypsum", "POP", "Grid", "PVC", "Wooden"]], ["Design", ["Single-level", "Multi-level", "Cove", "Floating"]], ["Specifications", ["Thickness", "Area", "Height", "Moisture resistance", "Fire performance"]]], cta: "Plan My Ceiling" },
  "wall-paneling": { title: "Wall Paneling", intro: "Explore finishes and installation requirements for a focused wall project.", sections: [["Materials", ["MDF", "WPC", "PVC", "Wood", "Stone", "Fluted panels"]], ["Finishes", ["Matte", "Gloss", "Woodgrain", "Textured"]], ["Specifications", ["Dimensions", "Thickness", "Application", "Installation"]]], cta: "Create My Wall Project" },
  flooring: { title: "Flooring Installation", intro: "Compare flooring materials by performance, finish, and installation method.", sections: [["Materials", ["Vitrified tile", "Porcelain", "Ceramic", "Marble", "Granite", "Wooden", "SPC", "Vinyl"]], ["Filters", ["Size", "Thickness", "Finish", "Color", "Water resistance", "Slip resistance", "Durability", "Price range"]], ["Project details", ["Area measurement", "Subfloor condition", "Installation method", "Warranty"]]], cta: "Find My Flooring" },
  "end-to-end-execution": { title: "End-to-End Execution", intro: "Run the complete journey from site assessment to a documented handover.", sections: [["Workflow", ["Project brief", "Site assessment", "Design", "BOQ / scope", "Material selection", "Professional selection"]], ["Execution", ["Quotation", "Contract", "Milestones", "Procurement", "Execution", "Quality checks", "Handover"]], ["Workspace", ["Tasks", "Files", "Messages", "Payments", "Issues", "Completion certificate"]]], cta: "Plan My Execution" },
};

export function generateStaticParams() { return Object.keys(journeys).map((slug) => ({ slug })); }

export default async function ServiceDiscoveryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const journey = journeys[slug] ?? journeys["full-home-interior-design"];
  return <main>
    <section className="bg-[var(--rv-slate)] py-14 text-white sm:py-20"><div className="page-shell"><Link href="/services" className="text-sm text-white/70 hover:text-white">Services / Discovery</Link><p className="mt-10 text-sm font-bold uppercase tracking-[.18em] text-[#f1b3a5]">Dedicated project journey</p><h1 className="font-display mt-3 max-w-4xl text-4xl leading-tight sm:text-6xl">{journey.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/75">{journey.intro}</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/customer/dashboard/projects/new" size="lg">{journey.cta} <ArrowRight size={18} /></ButtonLink><ButtonLink href="/professionals" variant="outline" size="lg" className="border-white/25 bg-white/5 text-white hover:bg-white/10">Find matched professionals <Search size={18} /></ButtonLink></div></div></section>
    <section className="page-shell py-12 sm:py-16"><div className="grid gap-5 lg:grid-cols-3">{journey.sections.map(([title, items]) => <article key={title} className="rounded-lg border border-[var(--rv-border)] bg-[var(--rv-surface)] p-6 shadow-[var(--rv-shadow-sm)]"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-[var(--rv-terracotta-soft)] text-[var(--rv-terracotta)]"><CheckCircle2 size={18} /></span><h2 className="font-display text-xl">{title}</h2></div><ul className="mt-6 grid gap-3 text-sm text-[var(--rv-ink-2)]">{items.map((item) => <li key={item} className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[var(--rv-terracotta)]" />{item}</li>)}</ul></article>)}</div></section>
    <section className="border-y border-[var(--rv-border)] bg-[var(--rv-surface-muted)] py-12"><div className="page-shell grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-bold text-[var(--rv-terracotta)]">Structured by Sajivo</p><h2 className="font-display mt-2 text-3xl">Turn discovery into a brief professionals can act on.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--rv-ink-2)]">Your selections stay attached to the project, so estimates, proposals, payments, and milestones have one source of truth.</p></div><ButtonLink href="/customer/dashboard/projects/new">Create project brief <FileText size={17} /></ButtonLink></div></section>
  </main>;
}
