import { ArrowRight, BadgeCheck, BriefcaseBusiness, ChartNoAxesCombined, FileCheck2, FolderOpen, MessageSquare, ShieldCheck } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";

export default function ForProfessionalsPage() {
  return (
    <>
      <section className="bg-white px-3 pb-4 pt-3 sm:px-5"><div className="relative mx-auto min-h-[560px] max-w-[1500px] overflow-hidden rounded-lg bg-[var(--rv-slate)]"><img src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=2200&q=88" alt="Interior professional working on a modern project" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/40 to-transparent" /><div className="relative flex min-h-[560px] max-w-2xl flex-col justify-center p-7 text-white sm:p-12 lg:p-16"><p className="text-sm font-bold text-[#f1b3a5]">Sajivo for professionals</p><h1 className="font-display mt-3 text-4xl leading-tight sm:text-6xl">Build your reputation. Win better-fit work.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-white/80">Discover structured project briefs, send polished proposals, showcase your work, and keep clients aligned from one workspace.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/register?role=designer" size="lg">Join as a designer</ButtonLink><ButtonLink href="/register?role=contractor" variant="outline" size="lg" className="border-white/30 bg-white text-[var(--rv-ink)]">Join as a contractor</ButtonLink></div></div></div></section>
      <section className="page-shell py-14 sm:py-20"><div className="max-w-2xl"><p className="text-sm font-bold text-[var(--rv-terracotta)]">A better way to run client work</p><h2 className="font-display mt-2 text-3xl sm:text-4xl">Tools built around the real project flow.</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[BriefcaseBusiness, "Relevant project discovery", "See structured briefs that match your role, services, and location."], [FileCheck2, "Professional proposals", "Present scope, pricing, timelines, and deliverables in a clear format."], [FolderOpen, "Portfolio builder", "Showcase completed work with services, location, and project details."], [ShieldCheck, "Verification badges", "Build trust with reviewed credentials and visible profile status."], [MessageSquare, "Shared workspace", "Keep project messages, files, activity, and decisions together."], [ChartNoAxesCombined, "Project visibility", "Track active work, status, and upcoming commitments at a glance."]].map(([Icon, title, text]) => <article key={title as string} className="rounded-lg border border-[var(--rv-border)] bg-white p-6"><Icon className="text-[var(--rv-terracotta)]" size={23} /><h3 className="mt-8 text-lg font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[var(--rv-ink-2)]">{text as string}</p></article>)}</div></section>
      <section className="border-y border-[var(--rv-border)] bg-white py-14 sm:py-20"><div className="page-shell grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><BadgeCheck size={28} className="fill-[var(--rv-moss)] text-white" /><h2 className="font-display mt-5 text-3xl sm:text-4xl">Your profile should do more than list services.</h2><p className="mt-4 leading-7 text-[var(--rv-ink-2)]">Help customers understand your style, expertise, service areas, project fit, pricing starting point, and track record before they contact you.</p><ButtonLink href="/register?role=designer" className="mt-7">Create your profile <ArrowRight size={17} /></ButtonLink></div><div className="grid gap-3 rounded-lg bg-[var(--rv-bg)] p-5 sm:grid-cols-2">{["Business identity", "Portfolio projects", "Services and areas", "Ratings and reviews", "Availability status", "Verification documents"].map((item) => <div key={item} className="flex items-center gap-3 rounded-md bg-white p-4 text-sm font-semibold"><BadgeCheck size={17} className="text-[var(--rv-moss)]" /> {item}</div>)}</div></div></section>
    </>
  );
}
