from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output/pdf/Sajivo_MVP_Landing_Page_Agency_Change_Request_Implementation_Report.pdf"
OUT.parent.mkdir(parents=True, exist_ok=True)
EVIDENCE = ROOT / "output/evidence"
ANNOTATED = ROOT / "output/annotated-evidence"
LIVE_ANNOTATED = ANNOTATED
REFS = [
    Path('/var/folders/jb/cq_njkqx5qb013k9_fs1214c0000gn/T/TemporaryItems/NSIRD_screencaptureui_ZEfOmZ/Screenshot 2026-08-11 at 11.31.53 PM.png'),
    Path('/var/folders/jb/cq_njkqx5qb013k9_fs1214c0000gn/T/TemporaryItems/NSIRD_screencaptureui_HCsooS/Screenshot 2026-08-11 at 11.32.08 PM.png'),
    Path('/var/folders/jb/cq_njkqx5qb013k9_fs1214c0000gn/T/TemporaryItems/NSIRD_screencaptureui_0fw55A/Screenshot 2026-08-11 at 11.32.49 PM.png'),
    Path('/var/folders/jb/cq_njkqx5qb013k9_fs1214c0000gn/T/TemporaryItems/NSIRD_screencaptureui_2BjkQ7/Screenshot 2026-08-11 at 11.33.09 PM.png'),
    Path('/var/folders/jb/cq_njkqx5qb013k9_fs1214c0000gn/T/TemporaryItems/NSIRD_screencaptureui_9Td7qX/Screenshot 2026-08-11 at 11.33.17 PM.png'),
]
styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='Cover', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=27, leading=33, textColor=colors.HexColor('#202b29'), spaceAfter=18))
styles.add(ParagraphStyle(name='H', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=18, leading=22, textColor=colors.HexColor('#202b29'), spaceAfter=10))
styles.add(ParagraphStyle(name='Sub', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=11, leading=14, textColor=colors.HexColor('#b74731'), spaceBefore=7, spaceAfter=5))
styles.add(ParagraphStyle(name='Body2', parent=styles['BodyText'], fontName='Helvetica', fontSize=9.2, leading=13.5, textColor=colors.HexColor('#343a36'), spaceAfter=7))
styles.add(ParagraphStyle(name='Small2', parent=styles['BodyText'], fontName='Helvetica', fontSize=7.8, leading=10.5, textColor=colors.HexColor('#626861'), spaceAfter=3))
styles.add(ParagraphStyle(name='Note', parent=styles['BodyText'], fontName='Helvetica-Bold', fontSize=9.2, leading=13, textColor=colors.HexColor('#202b29'), backColor=colors.HexColor('#fff0eb'), borderColor=colors.HexColor('#d35f45'), borderWidth=.5, borderPadding=7, spaceBefore=6, spaceAfter=9))
def P(text, style='Body2'): return Paragraph(text, styles[style])
def bullets(items): return [P('• ' + x) for x in items]
def table(rows, widths):
    t = Table([[P(str(c), 'Small2') for c in row] for row in rows], colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#202b29')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#f3f4f0')]),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#d9dbd5')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]))
    return t
story = [P('Sajivo MVP Landing Page Change Request', 'Cover'), P('Implementation and visual verification report', 'Sub'), Spacer(1, 18), P('Prepared from the supplied agency change request DOCX and five WhatsApp reference screenshots. This report records the implemented product-positioning, authentication, preference controls, and evidence capture for the Sajivo Next.js application.'), Spacer(1, 18), table([['Area','Result'],['Positioning','Project-centric homepage language and six-stage journey'],['Authentication','Working preview login with Supabase-first role resolution'],['Account UX','Obsolete account-path summary removed'],['Preferences','Light, grey, and dark themes plus English/Hindi control'],['Verification','Production build passed; browser dashboard navigation verified']], [45*mm,125*mm]), P('Implementation status: complete in the local workspace; deployment publication follows source verification.', 'Note'), PageBreak()]
pages = [
('1. Executive summary', ['The agency brief asked Sajivo to read as a project marketplace and management platform, not only a directory of interior designers.','The homepage now leads with the project journey: brief, discover, compare, hire, manage, complete.','The primary conversion action is Start a Project; discovery is Find Professionals.','The change keeps the existing premium visual language, dark workflow contrast, imagery, rounded cards, and restrained shadows.']),
('2. Source specification', ['The supplied DOCX was treated as the product-positioning source of truth.','It requested a project-centric marketplace, a clear client journey, professional and business ecosystems, structured briefs, transparent proposals, and a workspace concept.','The supplied screenshots were treated as acceptance references for the auth issue, footer copy, account-path removal, theme control, and language control.']),
('3. Header and navigation', ['Services is presented as Explore in the public navigation.','How it works is presented as How Sajivo Works.','The header primary CTA is Start a Project, which routes to the structured registration/project entry point.','Professionals and For professionals remain visible as distinct discovery and supply-side paths.','The mobile navigation retains four predictable destinations and keeps the primary action accessible.']),
('4. Hero positioning', ['The eyebrow now says: A clearer way to build, renovate and manage your project.','The headline is project-centric: Build, renovate and transform your space — with everyone on the same page.','The supporting text names professionals, suppliers, proposals, and management from start to completion.','The search field accepts project needs such as designer, contractor, and kitchen renovation.','Find Professionals submits the discovery action; Start a Project is the direct brief entry action.']),
('5. Service discovery', ['The homepage continues to load service data through the repository layer, using Supabase when configured and demo data as a local fallback.','Service cards remain useful as project-need entry points instead of decorative categories.','The landing page keeps progressive disclosure: homepage, service, professional, project.','The footer adds Vendors / Businesses to acknowledge the ecosystem without overwhelming the MVP.']),
('6. Six-stage workflow', ['The dark workflow section now communicates six steps: Create your brief, Discover, Compare, Hire, Manage, Complete.','Each step has supporting copy describing the user decision, not only a marketing label.','The section still preserves the original dark green/charcoal visual contrast requested by the agency brief.','The final handover and review outcome is explicit, making the intended platform loop understandable without a sales call.']),
('7. Ecosystem section', ['A new ecosystem block distinguishes Clients, Professionals, and Businesses.','Professionals are described broadly enough to support designers, contractors, and future specialists.','Businesses are acknowledged as retailers and future suppliers, avoiding unsupported Phase 2 promises.','The UI uses compact repeated cards so the homepage remains scannable.']),
('8. Project workspace section', ['A new workspace block communicates the product differentiator: one workspace for the entire project.','The visible concepts are Overview, Budget, Milestones, Documents, People, Messages, Issues, and Payments.','The copy presents the workspace as a real product surface while avoiding claims of unsupported guarantees.','The section follows the brief recommendation to show the future client dashboard concept on the landing page.']),
('9. Transparency and final CTA', ['A new More transparency. Fewer surprises. section lists supportable MVP behaviors: profiles, scope, proposals, milestones, documents, and reviews.','The wording avoids guaranteed, 100% verified, best price, and zero disputes claims.','The final CTA reads Your project starts with one brief.','The CTA routes to the same project/account entry point used by the header.']),
('10. Login failure diagnosis', ['The original login route treated any missing profiles row as a fatal 500 response, even after Supabase Auth had accepted credentials.','This created the reported symptom: a user could sign up or authenticate but could not enter the dashboard.','The corrected route now uses maybeSingle for the profile read.','When a profile exists, its database primary_role remains authoritative.','When the preview seed is absent, the documented customer demo account resolves through a constrained preview fallback.']),
('11. Signup and account model', ['Signup remains Supabase Auth-first and sends account_type, business_account_type, business_role, and primary_role metadata.','The database trigger can create the corresponding profile and business account when the migration is installed.','The registration form keeps only the two top-level user account choices: Client account and Business account.','Business choices are limited to the requested phase-one professional roles and retailer vendor role.','The obsolete Account path summary block was removed entirely from the form.']),
('12. Theme controls', ['The global preference control provides Light, Grey, and Dark buttons with accessible names and pressed states.','Light uses the original warm off-white Sajivo palette.','Grey uses a Spotify-inspired charcoal scale centered on #121212, #1f1f1f, and #b3b3b3.','Dark uses a cooler navy-charcoal scale for a distinct third mode.','The selected theme is stored in localStorage and applied through document data-theme so it persists across navigation.']),
('13. Language control', ['The global language button switches between EN and हिन्दी.','The control updates the document language attribute and persists the choice locally.','The button has an explicit accessible label: Switch language to Hindi or English.','This release establishes the preference surface and language state; full copy translation can be expanded through the same dictionary boundary without changing layout components.']),
('14. Supabase integration', ['The app continues to use the configured Supabase project URL from environment variables; no credential is written into the report or source.','Login uses Supabase Auth and reads public.profiles for the role.','Signup writes Auth user metadata used by the account-hierarchy trigger.','Repository reads use Supabase when configured and preserve demo fallback data for local preview routes.','The implementation does not place screenshots or WhatsApp references in the application bundle.']),
('15. Responsive and accessibility checks', ['The preference control uses button titles, accessible names, and pressed state semantics.','The auth forms retain labels, autocomplete attributes, password visibility controls, and keyboard-submit behavior.','The hero search and CTAs remain stacked on small screens, avoiding horizontal overflow.','The six workflow cards reflow from three columns to a responsive grid.','All tested public pages returned a nonblank DOM snapshot in the local browser.']),
('16. Browser verification', ['Opened /login in the local preview.','Verified the prefilled demo account fields.','Activated Sign in.','Confirmed navigation to /customer/dashboard.','Observed the customer workspace navigation and dashboard shell.','Captured implementation evidence for landing, register, login, grey theme, dark theme, and Hindi control.']),
('17. Build verification', ['npm run build completed successfully after the changes.','TypeScript checking completed without errors.','Next.js generated the full route set, including auth API routes, public pages, dashboards, estimator, and professional/vendor surfaces.','The report is generated outside the app source so visual evidence is not deployed.']),
('18. Acceptance mapping', ['P0 Start a Project: implemented in header, hero, and final CTA.','P0 Find Professionals: implemented in hero search and professional links.','P0 project-centric language: implemented in hero, workflow, ecosystem, and workspace copy.','Auth issue: fixed for Supabase-first login and preview demo fallback.','Theme request: implemented with light, grey, and dark modes.','Language request: implemented with English/Hindi preference control.']),
('19. Release notes', ['The source change is ready for commit and Vercel deployment after the final build.','Remote Supabase signup should be tested with a staging email because email-confirmation settings are project-specific.','The documented demo credential is intentionally limited to the preview customer path.','Screenshots used for this report remain local evidence and are not added to GitHub or the live app.']),
('20. Conclusion', ['Sajivo now presents the requested product direction: from project brief to completion.','The client can start a project or find professionals from the first viewport.','The auth flow no longer blocks preview login solely because a profile row is missing.','The removed account-path UI, theme selector, language selector, and report evidence directly address the supplied change screenshots.','The next operational step is deployment publication and a final remote Supabase acceptance pass.']),
]
for title, items in pages:
    story += [P(title, 'H'), P('Implementation notes and verification evidence', 'Sub')] + bullets(items)
    if title.startswith('11.'):
        story.append(P('Account hierarchy retained: Client account or Business account; Business then branches to Professional or Vendor, with phase-one role restrictions.', 'Note'))
    if title.startswith('12.'):
        story.append(P('Evidence: the implementation control is visible globally in the top-right preference pill and is persisted locally.', 'Note'))
    story.append(PageBreak())
for i, path in enumerate([LIVE_ANNOTATED/'01-live-landing.png', LIVE_ANNOTATED/'02-live-services.png', LIVE_ANNOTATED/'03-live-professionals.png', LIVE_ANNOTATED/'04-live-how-it-works.png', LIVE_ANNOTATED/'05-live-for-professionals.png', LIVE_ANNOTATED/'06-live-register.png', LIVE_ANNOTATED/'07-live-login.png', LIVE_ANNOTATED/'08-live-customer-dashboard.png', ANNOTATED/'01-landing.png', ANNOTATED/'02-register.png', ANNOTATED/'03-login.png', ANNOTATED/'04-grey-theme.png', ANNOTATED/'05-dark-theme.png', ANNOTATED/'06-hindi-control.png'] + REFS):
    if path.exists():
        story += [P(f'Appendix evidence {i+1}', 'H'), P(path.name, 'Sub'), Image(str(path), width=170*mm, height=95*mm), Spacer(1, 8), P('Annotation: captured or supplied reference evidence for the corresponding workflow and change request. Screenshots are included in this PDF appendix only.', 'Note'), PageBreak()]
def footer(canvas, doc):
    canvas.saveState(); canvas.setStrokeColor(colors.HexColor('#dedfda')); canvas.line(18*mm,14*mm,192*mm,14*mm); canvas.setFont('Helvetica',7.5); canvas.setFillColor(colors.HexColor('#7a817a')); canvas.drawString(18*mm,9*mm,'Sajivo | MVP Landing Page Change Request'); canvas.drawRightString(192*mm,9*mm,f'Page {doc.page}'); canvas.restoreState()
SimpleDocTemplate(str(OUT), pagesize=A4, rightMargin=18*mm, leftMargin=18*mm, topMargin=16*mm, bottomMargin=19*mm, title='Sajivo MVP Landing Page Agency Change Request Implementation Report').build(story, onFirstPage=footer, onLaterPages=footer)
print(OUT)
